# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import copilot_bridge_pb2 as copilot__bridge__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in copilot_bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CopilotBridgeServiceStub(object):
    """─── Service ────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/copilot_bridge.CopilotBridgeService/GetStatus',
                request_serializer=copilot__bridge__pb2.StatusRequest.SerializeToString,
                response_deserializer=copilot__bridge__pb2.StatusReply.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/copilot_bridge.CopilotBridgeService/ListModels',
                request_serializer=copilot__bridge__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=copilot__bridge__pb2.ListModelsReply.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/copilot_bridge.CopilotBridgeService/Chat',
                request_serializer=copilot__bridge__pb2.ChatRequest.SerializeToString,
                response_deserializer=copilot__bridge__pb2.ChatReply.FromString,
                _registered_method=True)
        self.ChatStream = channel.unary_stream(
                '/copilot_bridge.CopilotBridgeService/ChatStream',
                request_serializer=copilot__bridge__pb2.ChatRequest.SerializeToString,
                response_deserializer=copilot__bridge__pb2.ChatStreamChunk.FromString,
                _registered_method=True)


class CopilotBridgeServiceServicer(object):
    """─── Service ────────────────────────────────────────────────────────────────

    """

    def GetStatus(self, request, context):
        """Get server status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """List available models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Send chat request — full response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request, context):
        """Send chat request — streaming response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CopilotBridgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=copilot__bridge__pb2.StatusRequest.FromString,
                    response_serializer=copilot__bridge__pb2.StatusReply.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=copilot__bridge__pb2.ListModelsRequest.FromString,
                    response_serializer=copilot__bridge__pb2.ListModelsReply.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=copilot__bridge__pb2.ChatRequest.FromString,
                    response_serializer=copilot__bridge__pb2.ChatReply.SerializeToString,
            ),
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=copilot__bridge__pb2.ChatRequest.FromString,
                    response_serializer=copilot__bridge__pb2.ChatStreamChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'copilot_bridge.CopilotBridgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('copilot_bridge.CopilotBridgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CopilotBridgeService(object):
    """─── Service ────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/copilot_bridge.CopilotBridgeService/GetStatus',
            copilot__bridge__pb2.StatusRequest.SerializeToString,
            copilot__bridge__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/copilot_bridge.CopilotBridgeService/ListModels',
            copilot__bridge__pb2.ListModelsRequest.SerializeToString,
            copilot__bridge__pb2.ListModelsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/copilot_bridge.CopilotBridgeService/Chat',
            copilot__bridge__pb2.ChatRequest.SerializeToString,
            copilot__bridge__pb2.ChatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/copilot_bridge.CopilotBridgeService/ChatStream',
            copilot__bridge__pb2.ChatRequest.SerializeToString,
            copilot__bridge__pb2.ChatStreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
