# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: copilot_bridge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'copilot_bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63opilot_bridge.proto\x12\x0e\x63opilot_bridge\"\x0f\n\rStatusRequest\"l\n\x0bStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x15\n\rdefault_model\x18\x03 \x01(\t\x12\x17\n\x0frequests_served\x18\x04 \x01(\x05\x12\x0f\n\x07version\x18\x05 \x01(\t\"\x13\n\x11ListModelsRequest\"<\n\x0fListModelsReply\x12)\n\x06models\x18\x01 \x03(\x0b\x32\x19.copilot_bridge.ModelInfo\"p\n\tModelInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06vendor\x18\x03 \x01(\t\x12\x0e\n\x06\x66\x61mily\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\t\x12\x18\n\x10max_input_tokens\x18\x06 \x01(\x05\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"r\n\x0b\x43hatRequest\x12-\n\x08messages\x18\x01 \x03(\x0b\x32\x1b.copilot_bridge.ChatMessage\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0e\n\x06vendor\x18\x03 \x01(\t\x12\x15\n\rsystem_prompt\x18\x04 \x01(\t\"7\n\tChatReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"U\n\x0f\x43hatStreamChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x14\n\x0ctotal_length\x18\x04 \x01(\x05\x32\xbf\x02\n\x14\x43opilotBridgeService\x12G\n\tGetStatus\x12\x1d.copilot_bridge.StatusRequest\x1a\x1b.copilot_bridge.StatusReply\x12P\n\nListModels\x12!.copilot_bridge.ListModelsRequest\x1a\x1f.copilot_bridge.ListModelsReply\x12>\n\x04\x43hat\x12\x1b.copilot_bridge.ChatRequest\x1a\x19.copilot_bridge.ChatReply\x12L\n\nChatStream\x12\x1b.copilot_bridge.ChatRequest\x1a\x1f.copilot_bridge.ChatStreamChunk0\x01\x42\x15\xaa\x02\x12\x43opilotBridge.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'copilot_bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\022CopilotBridge.Grpc'
  _globals['_STATUSREQUEST']._serialized_start=40
  _globals['_STATUSREQUEST']._serialized_end=55
  _globals['_STATUSREPLY']._serialized_start=57
  _globals['_STATUSREPLY']._serialized_end=165
  _globals['_LISTMODELSREQUEST']._serialized_start=167
  _globals['_LISTMODELSREQUEST']._serialized_end=186
  _globals['_LISTMODELSREPLY']._serialized_start=188
  _globals['_LISTMODELSREPLY']._serialized_end=248
  _globals['_MODELINFO']._serialized_start=250
  _globals['_MODELINFO']._serialized_end=362
  _globals['_CHATMESSAGE']._serialized_start=364
  _globals['_CHATMESSAGE']._serialized_end=408
  _globals['_CHATREQUEST']._serialized_start=410
  _globals['_CHATREQUEST']._serialized_end=524
  _globals['_CHATREPLY']._serialized_start=526
  _globals['_CHATREPLY']._serialized_end=581
  _globals['_CHATSTREAMCHUNK']._serialized_start=583
  _globals['_CHATSTREAMCHUNK']._serialized_end=668
  _globals['_COPILOTBRIDGESERVICE']._serialized_start=671
  _globals['_COPILOTBRIDGESERVICE']._serialized_end=990
# @@protoc_insertion_point(module_scope)
